---
title: "Getting started with deep learning in R"
description: |
  More and more fields are profiting from the use of deep learning, and with the R keras, tensorflow and related packages, you can do deep learning directly in R. In this post, we want to give some orientation as to how to best get started.
author:
  - name: Sigrid Keydana
    affiliation: RStudio
    affiliation_url: https://www.rstudio.com/
slug: keydana2018gettingstarted
date: 09-03-2018
categories:
  - Keras
output:
  radix::radix_article:
    self_contained: false
preview: images/digits.png
---


There are good reasons to get into deep learning: Deep learning has been outperforming the respective "classical" techniques in areas like image recognition and natural language processing for a while now, and it brings interesting insights even to the analysis of tabular data. For many R users potentially interested in deep learning, the hurdle is not an anticipation of a bit of math creeping up (as many have a background in statistics or empirical sciences). The question is how to get started in an efficient way.

This post will give an overview of materials that should be useful. And if you don't have that background in statistics or similar: Further down, we will also present a few helpful resources to catch up with "the math".

## Keras

The easiest way to get started is using the Keras API. It is a high-level, declarative (in feel) way of specifying a model, training and testing it, originally developed in [Python](http://keras.io) by Francois Chollet and ported to R by JJ Allaire.

Check out the tutorials on the [Keras website](https://tensorflow.rstudio.com/keras/): They introduce basic tasks like classification and regression, as well as basic workflow elements like saving and restoring models, or assessing model performance.

Once you've seen the basics, the website also has more advanced information as to implementing custom logic, monitoring and tuning, as well as using and adapting pre-trained models.

If you don't yet have prior experience in deep learning, you might want a bit more background. [Deep Learning with R](https://www.amazon.com/Deep-Learning-R-Francois-Chollet/dp/161729554X) by Francois Chollet and JJ Allaire is an excellent introduction to deep learning that presents the high-level concepts in a very intellegible way.

At the same time, it contains lots of ready-to-use code, presenting examples for all the major architectures and use cases (including fancy stuff like variational autoencoders and GANs). 
There are also [companion videos](https://www.manning.com/livevideo/deep-learning-with-r-in-motion) to the book.

## Inspiration

If you're not pursuing a specific goal, but in general curious about what can be done with deep learning, a good place to follow is the [RStudio TensorFlow blog](https://tensorflow.rstudio.com/blog.html). There, you'll find applications of deep learning to business as well as scientific tasks, as well as technical expositions and introductions to new features.

The [Gallery](https://tensorflow.rstudio.com/learn/gallery.html) displays case studies by topic so you can browse for ideas.

## Reality

Once the ideas are there, realization should follow, and for most of us the question will be: Where can I actually _train_ that model? As soon as real-world-size images are involved, or medical images, or other kinds of higher-dimensional data, training on your laptop won't be an option any more.

There are different ways you can train in the cloud: 

Firstly, [cloud server instances](https://tensorflow.rstudio.com/tools/cloud_server_gpu.html) on Amazon EC2 and Google Compute Engine, with RStudio Server and the R TensorFlow package suite preinstalled.

Secondly, [Paperspace templates](https://tensorflow.rstudio.com/tools/cloud_desktop_gpu.html), again with the R TensorFlow package suite ready for use.

Thirdly, the _cloudml_ package provides an [interface to the Google Cloud Machine Learning engine](https://tensorflow.rstudio.com/tools/cloudml/articles/getting_started.html)  that lets you train models nearly transparently in the cloud.

## More background

If you don't have a very "mathy" background, you might feel that you'd like to supplement the concepts-focused approach from _Deep Learning with R_ with a bit more low-level basics (just as some people feel the need to know at least a bit of Assembler when learning a high-level language). 
Personal recommendations for such cases would include Andrew Ng's [deep learning specialization](https://www.coursera.org/specializations/deep-learning) on Coursera (videos are free to watch), and the book(s) and recorded lectures on linear algebra by [Gilbert Strang](https://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/video-lectures/).

## Getting help

Last not least, should you encounter problems with the software (or with mapping your task to runnable code), a good idea is to create a github issue in the respective repository, e.g., [rstudio/keras](https://github.com/rstudio/keras/).
Best of luck for your deep learning journey with R!


